import {Expedition,ITEMS,STAGES} from './engine.js';
import {WorldArt,icon} from './art.js';
import {RuneAudio} from './audio.js';
const $=id=>document.getElementById(id);
const STORE='rune-expedition-v1';
function readStore(){try{return JSON.parse(localStorage.getItem(STORE)||'{}')||{};}catch{return {};}}
let saved=readStore(),lang=saved.lang==='en'?'en':'zh',modalType='',lastFocus=null,resultData=null,bannerTimer,noticeTimer,toastTimer;
const L=()=>lang==='zh'?0:1,txt=(zh,en)=>lang==='zh'?zh:en;
const g=new Expedition(),art=new WorldArt($('scene')),audio=new RuneAudio();audio.enabled=saved.sound!==false;
function persist(){try{localStorage.setItem(STORE,JSON.stringify(saved));}catch{}}
function seconds(t){return Math.floor(t/60).toString().padStart(2,'0')+':'+Math.floor(t%60).toString().padStart(2,'0');}
function itemName(id){return ITEMS[id].name[L()];}
function modal(html,type){lastFocus=document.activeElement;$('overlayContent').innerHTML=html;$('overlay').hidden=false;modalType=type;requestAnimationFrame(()=>{$('overlayContent').querySelector('button')?.focus({preventScroll:true});});}
function closeModal(){const old=modalType;modalType='';$('overlay').hidden=true;if(g.mode==='paused')g.resume();else if(g.mode==='loot')renderLoot();else if(g.mode==='result'&&old!=='result')renderResult();else if(lastFocus?.isConnected)lastFocus.focus({preventScroll:true});}
function toast(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2300);}
function notice(message,danger=false,duration=2800){$('combatNotice').textContent=message;$('combatNotice').classList.toggle('danger',danger);$('combatNotice').style.opacity=1;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('combatNotice').style.opacity=0,duration);}
function setLanguage(){
  document.documentElement.lang=lang==='zh'?'zh-CN':'en';$('language').textContent=lang==='zh'?'EN':'中';$('language').setAttribute('aria-label',txt('Switch to English','切换为中文'));
  $('gameTitle').innerHTML=txt('符文远征','RUNE<br>EXPEDITION');$('gameTitle').classList.toggle('english',lang==='en');document.querySelector('.english-title').textContent=txt('RUNE EXPEDITION','A DARK FANTASY ADVENTURE');
  $('homeEyebrow').textContent=txt('第一章 · 灰烬之门','CHAPTER I · THE ASHEN GATE');$('tagline').textContent=txt('碑文已碎，守门者仍在。\n带回那枚熄灭的符文。','The inscription is broken. The guardian remains.\nBring the forgotten rune back to life.');
  $('heroTag').textContent=txt('最后的守誓者','THE LAST OATHKEEPER');$('heroClass').textContent=txt('符文骑士','RUNE KNIGHT');$('startLabel').textContent=txt('踏入遗迹','ENTER THE RUINS');$('sessionNote').textContent=txt('剑盾连招 · 手动 / 自动 · 三章试炼','SWORD & SHIELD · MANUAL / AUTO · 3 CHAPTERS');$('howTo').textContent=txt('远征指南','HOW TO PLAY');$('recordsButton').textContent=txt('远征记录','RUN HISTORY');
  $('attackIcon').innerHTML=icon('sword');$('dodgeIcon').innerHTML=icon('dodge');$('staminaLabel').textContent=txt('耐力','STAMINA');$('dodgeLabel').textContent=txt('闪避','DODGE');$('dodgeHint').textContent=txt('22耐力 · 空格','22 STA · SPACE');$('burstLabel').textContent=txt('符文爆发','RUNE BURST');$('guardLabel').textContent=txt('按住举盾','HOLD TO GUARD');$('burstHint').textContent=txt('30耐力 · E','30 STA · E');$('guardHint').textContent=txt('临击格挡 · Q / K','TIMED PARRY · Q / K');$('heroName').textContent=txt('守誓者','OATHKEEPER');$('bossName').textContent=txt('缄默之王','THE HOLLOW KING');
  $('pause').setAttribute('aria-label',txt('暂停游戏','Pause game'));$('scene').setAttribute('aria-label',txt('符文远征战场','Rune Expedition battlefield'));$('homeMark').setAttribute('aria-label',txt('作品说明','About this demo'));updateSound();updateUI();
  if(modalType==='loot')renderLoot();if(modalType==='pause')renderPause();if(modalType==='howto')renderHowto();if(modalType==='about')renderAbout();if(modalType==='history')renderHistory();if(modalType==='result')renderResult();if(modalType==='details')renderDetails();
  if(!$('stageBanner').hidden&&g.mode!=='home')$('stageBanner').innerHTML=`<small>${STAGES[g.stage].subtitle[L()]}</small><strong>${STAGES[g.stage].name[L()]}</strong>`;
  if(g.mode==='battle')notice(txt('点击挥剑 · 按住举盾 · 点地走位','TAP TO ATTACK · HOLD GUARD · TAP GROUND TO MOVE'),false,2200);
}
function updateSound(){$('sound').innerHTML=icon(audio.enabled?'sound':'mute');$('sound').setAttribute('aria-label',audio.enabled?txt('关闭声音','Mute sound'):txt('开启声音','Enable sound'));$('sound').setAttribute('aria-pressed',String(audio.enabled));}
function updateUI(){
 const h=g.hero,active=g.mode!=='home';$('home').hidden=active;$('hud').hidden=!active;$('controls').hidden=!active;$('pause').hidden=!['battle','paused'].includes(g.mode);if(!active)return;
 $('chapterLabel').textContent=`0${g.stage+1} / ${STAGES[g.stage].name[L()]}`;$('waveLabel').textContent=g.stage===2?txt('最终试炼','FINAL TRIAL'):txt(`第 ${Math.max(1,g.wave)} / 3 波`,`WAVE ${Math.max(1,g.wave)} / 3`);
 $('healthText').textContent=`${Math.ceil(h.hp)} / ${h.maxHp}`;$('healthFill').style.width=(h.hp/h.maxHp*100)+'%';$('staminaFill').style.width=h.stamina+'%';$('staminaText').textContent=Math.floor(h.stamina);$('attackStat').textContent=txt('攻击 ','ATK ')+h.attack;$('critStat').textContent=txt('暴击 ','CRIT ')+Math.round(h.crit*100)+'%';$('goldStat').textContent=txt('灵魂碎片 ','SOULS ')+(g.stats?.coins||0);
 const boss=g.enemies.find(e=>e.kind==='boss'&&!e.dying);$('bossHud').hidden=!boss;if(boss){$('bossHealth').textContent=`${Math.ceil(boss.hp)} / ${boss.maxHp}`;$('bossFill').style.width=boss.hp/boss.maxHp*100+'%';}
 for(const [name,cd,total,cost]of[['burst',h.burstCd,8,30],['dodge',h.dodgeCd,2.2,22]]){const b=$(name);b.classList.toggle('on-cooldown',cd>.03);b.style.setProperty('--cd',Math.min(1,cd/total));$(name+'Cd').textContent=cd<1?cd.toFixed(1)+'s':Math.ceil(cd)+'s';b.disabled=cd>0||h.stamina<cost||g.mode!=='battle'||(name==='burst'&&!!(h.action||h.dodge||h.guarding));}
 $('guard').disabled=g.mode!=='battle'||h.guardLock>0||(!h.guarding&&h.stamina<8);$('guard').classList.toggle('held',h.guarding);$('guard').setAttribute('aria-pressed',String(h.guarding));$('attack').disabled=g.mode!=='battle'||!!h.dodge||h.guardLock>0;
 $('attack').classList.toggle('counter-ready',h.counter>0);$('attackLabel').textContent=h.counter>0?txt('破绽反击','RIPOSTE'):h.guarding?txt('盾击','SHIELD BASH'):txt('挥剑','SWORD ATTACK');$('attackHint').textContent=h.counter>0?txt('立即点按 · 强力刺击','TAP NOW · HEAVY THRUST'):h.guarding?txt('20耐力 · 打断敌人','20 STA · INTERRUPT'):txt('连续点按三连击 · J','TAP FOR 3-HIT COMBO · J');
 $('autoMode').textContent=h.auto?txt('自动攻击 · 点击改手动','AUTO · SWITCH TO MANUAL'):txt('手动攻击 · 点击改自动','MANUAL · SWITCH TO AUTO');$('autoMode').setAttribute('aria-pressed',String(h.auto));$('autoMode').disabled=g.mode!=='battle';
 const combo=h.action?.kind==='sword'?h.action.index+1:h.comboTime>0?h.combo:0;$('comboState').textContent=h.counter>0?txt(`反击窗口 ${h.counter.toFixed(1)}s`,`RIPOSTE ${h.counter.toFixed(1)}s`):txt(`连招 ${combo} / 3`,`COMBO ${combo} / 3`);$('comboState').classList.toggle('counter-ready',h.counter>0);
 $('battleHint').textContent=h.guardLock>0?txt('架势破碎 · 暂时无法举盾','GUARD BROKEN · RECOVERING'):h.counter>0?txt('完美格挡！点击挥剑发动反击','PERFECT PARRY! TAP ATTACK TO RIPOSTE'):h.guarding?txt('保持举盾减伤 · 配合挥剑可盾击','HOLD TO BLOCK · TAP ATTACK TO BASH'):h.pendingAttack?txt('正在接近目标，随后挥剑','APPROACHING YOUR TARGET'):txt('点地走位 · 橙色攻击可挡 · 红圈请躲开','TAP GROUND TO MOVE · GUARD GOLD · DODGE RED');
 const equipment=h.items.map(id=>`<span>${icon(ITEMS[id].icon)}${itemName(id)}</span>`).join('');if($('equipped').innerHTML!==equipment)$('equipped').innerHTML=equipment;
 document.querySelectorAll('.chapter-progress i').forEach((el,i)=>el.className=i<g.stage?'done':i===g.stage?'current':'');fitArena();
}
function fitArena(){if($('controls').hidden)return;const r=$('game').getBoundingClientRect(),floorBottom=($('controls').getBoundingClientRect().top-r.top)/art.scale-18;art.battleOffset=Math.min(art.offset+160,floorBottom-410);g.setBounds(floorBottom-art.battleOffset);}
function renderLoot(){const chapter=g.stage;modal(`<div class="eyebrow">${txt('遗迹馈赠','RELIC DISCOVERED')}</div><h2 id="overlayTitle">${txt('选择你的力量','CHOOSE YOUR POWER')}</h2><p class="subcopy">${txt('每次选择，都会改变接下来的战斗。','Every choice shapes the battles ahead.')}</p><div class="loot-list">${g.choices.map(id=>{const it=ITEMS[id];return `<button class="loot-card" data-item="${id}"><span class="item-art" style="color:${it.color}">${icon(it.icon)}</span><span><strong>${it.name[L()]}</strong><small>${it.desc[L()]}</small><span class="item-tag">${it.tag[L()]}</span></span><span class="select-arrow">›</span></button>`;}).join('')}</div><p class="recovery-note">${txt('选择后回复 40% 最大生命，并重置技能冷却。','Restore 40% of max HP and reset skill cooldowns.')}</p><p class="small-note">${txt('下一站：','NEXT: ')}${STAGES[chapter+1].name[L()]}</p>`,'loot');}
function renderPause(){modal(`<div class="eyebrow">${txt('暂歇于遗迹之间','A MOMENT BETWEEN BATTLES')}</div><h2 id="overlayTitle">${txt('远征已暂停','EXPEDITION PAUSED')}</h2><p class="subcopy">${txt('深呼吸。下一次挥剑，为你而起。','Take a breath. The next strike is yours.')}</p><button class="primary-button" data-action="resume">${txt('继续远征','RESUME')}</button><button class="secondary-button" data-action="howto">${txt('查看远征指南','HOW TO PLAY')}</button><button class="text-button" data-action="home">${txt('结束本局，返回入口','END RUN & RETURN')}</button>`,'pause');}
function renderHowto(){const rows=[
 [txt('剑由你挥，连击由你衔接','Your sword. Your timing.'),txt('默认手动，骑士自动接近目标。点按挥剑，连续点按衔接斜劈、反斩、刺击；最多预存下一剑。可随时切换自动攻击。','Manual by default: the knight approaches a target, but you swing. Tap for slash, reverse slash, then thrust; only one next hit is queued. Toggle Auto at any time.')],
 [txt('举盾，抓住反击机会','Guard, then riposte.'),txt('按住举盾抵挡正面攻击。命中前约0.3秒举盾可完美格挡，随后2.2秒内挥剑可反击。平时按住盾再点挥剑可盾击打断小怪。注意耐力和背后的敌人。','Hold Guard to block frontal hits. Raise it about 0.3s before impact for a perfect parry, then attack within 2.2s to riposte. Hold Guard and tap Attack to shield-bash smaller foes. Watch stamina and your back.')],
 [txt('站位比硬扛更重要','Move before the impact.'),txt('点击地面移动，点击敌人切换目标。橙色扇形可格挡；红色圆圈是无法格挡的震击，走出范围或用闪避穿过命中瞬间。符文爆发只伤害近处敌人。','Tap the ground to move or a foe to target it. Guard gold attacks; red circles cannot be blocked. Leave the circle or dodge through the impact. Rune Burst hits nearby enemies.')]
 ];modal(`<div class="eyebrow">FIELD GUIDE</div><h2 id="overlayTitle">${txt('剑盾战斗指南','SWORD & SHIELD')}</h2>${rows.map(([title,copy],i)=>`<div class="howto-row"><span>0${i+1}</span><div><strong>${title}</strong><p>${copy}</p></div></div>`).join('')}<p class="small-note">${txt('电脑：WASD / 方向键移动；J / 1挥剑；Q / K / 2按住盾；空格 / L闪避；E符文爆发；M切换模式；Esc暂停。','KEYBOARD: WASD / arrows move; J / 1 attack; hold Q / K / 2 to guard; Space / L dodge; E burst; M toggle Auto; Esc pause.')}</p><button class="secondary-button" data-action="close">${txt('明白了','GOT IT')}</button>`,'howto');}
function renderAbout(){modal(`<div class="eyebrow">AN ORIGINAL DEMO BY CASSIE</div><h2 id="overlayTitle">${txt('符文远征','RUNE EXPEDITION')}</h2><p class="subcopy">${txt('一段关于抉择、成长与最后一击的暗黑奇幻远征。','A dark-fantasy expedition about choices, growth, and the final strike.')}</p><div class="howto-row"><span>ᛟ</span><div><strong>${txt('小小旅程，完整冒险','A small journey. A complete adventure.')}</strong><p>${txt('三场战斗、六件可选装备、一个最终Boss。支持中英文切换，手机与电脑均可试玩。','Three battles, six selectable relics, and one final boss. Play in Chinese or English, on mobile or desktop.')}</p></div></div><p class="small-note">${txt('这是借助 AI 编程工具制作的个人原创试玩作品。美术由程序绘制，音乐与音效实时合成。战斗记录仅保存在当前浏览器，可在远征记录中清除。','An original personal demo built with AI coding assistance. Artwork is drawn procedurally; music and sound are synthesized in real time. Run history stays in this browser and can be cleared.')}</p><button class="secondary-button" data-action="close">${txt('返回','BACK')}</button>`,'about');}
function renderResult(){if(!resultData)return;const {won,stats}=resultData;modal(`<div class="result-seal ${won?'':'defeat'}">${won?'ᛟ':'ᚾ'}</div><div class="eyebrow">${won?'EXPEDITION COMPLETE':'THE OATH REMAINS'}</div><h2 id="overlayTitle">${won?txt('符文重燃','THE RUNE AWAKENS'):txt('誓约未尽','RISE AGAIN')}</h2><p class="subcopy">${won?txt('长夜退去。你带回了遗迹最后的光。','The long night recedes. You return with its final light.'):txt('这次远征暂告结束。换一种选择，再次出发。','This expedition ends here. A new choice may change your fate.')}</p><div class="result-stats"><div><strong>${seconds(stats.time)}</strong><span>${txt('战斗用时','BATTLE TIME')}</span></div><div><strong>${stats.kills}</strong><span>${txt('击败敌人','ENEMIES SLAIN')}</span></div><div><strong>${stats.damage.toLocaleString()}</strong><span>${txt('累计伤害','TOTAL DAMAGE')}</span></div></div><div class="result-build">${stats.items.map(id=>`<span>${itemName(id)}</span>`).join('')}</div><p class="result-tip">${won?txt('下一次，试试不同的装备组合。','Try a different relic combination on your next run.'):txt('橙色攻击抓准时机格挡反击，红圈震击需要走位或闪避。','Parry gold attacks and riposte. Move or dodge out of red ground attacks.')}</p><button class="primary-button" data-action="restart">${txt('再次远征','ANOTHER EXPEDITION')}</button><button class="secondary-button" data-action="details">${txt('查看战斗回顾','VIEW BATTLE RECAP')}</button><button class="text-button" data-action="home">${txt('返回入口','RETURN TO THE GATE')}</button>`,'result');}
function renderDetails(){const s=resultData?.stats;if(!s)return;const rows=[[txt('战斗用时','Battle time'),seconds(s.time)],[txt('完成关卡','Stages cleared'),`${s.stages.length} / 3`],[txt('累计伤害','Damage dealt'),s.damage],[txt('承受伤害','Damage received'),s.received],[txt('护盾抵挡','Damage blocked'),s.blocked],[txt('暴击次数','Critical hits'),s.crits],[txt('爆发使用','Rune Bursts'),s.burst],[txt('举盾次数','Guards raised'),s.guard],[txt('完美格挡','Perfect parries'),s.perfectGuards],[txt('反击次数','Ripostes'),s.counters||0],[txt('三段终结','Combo finishers'),s.finishers||0],[txt('盾击次数','Shield bashes'),s.bashes||0],[txt('闪避次数','Dodges'),s.dodges||0],[txt('灵魂碎片','Soul shards'),s.coins]];modal(`<div class="eyebrow">BATTLE RECAP</div><h2 id="overlayTitle">${txt('每次选择都有回响','EVERY CHOICE ECHOES')}</h2><table class="data-table">${rows.map(([k,v])=>`<tr><td>${k}</td><td>${v}</td></tr>`).join('')}</table><p class="small-note">${txt('以上为本局实际记录。仅保存在当前浏览器，不上传个人信息。','Actual results from this run. Stored in this browser only.')}</p><button class="secondary-button" data-action="export">${txt('保存本局记录','SAVE RUN DATA')}</button><button class="text-button" data-action="result">${txt('返回结算','BACK TO RESULTS')}</button>`,'details');}
function renderHistory(){const runs=saved.runs||[];modal(`<div class="eyebrow">YOUR EXPEDITIONS</div><h2 id="overlayTitle">${txt('远征记录','RUN HISTORY')}</h2><p class="subcopy">${runs.length?txt('保存在此浏览器的最近 5 次远征。','Your last five expeditions on this browser.'):txt('遗迹正等待你的第一步。','The ruins await your first step.')}</p>${runs.map((r,i)=>`<button class="loot-card" data-history="${i}"><span class="item-art">${r.won?'ᛟ':'ᚾ'}</span><span><strong>${r.won?txt('符文重燃','RUNE AWAKENED'):txt('誓约未尽','OATH UNFINISHED')}</strong><small>${seconds(r.time)} · ${r.kills} ${txt('击败','slain')} · ${r.items.map(itemName).join(' / ')||txt('初始装备','Starting gear')}</small></span><span class="select-arrow">›</span></button>`).join('')}<button class="secondary-button" data-action="close">${txt('返回','BACK')}</button>${runs.length?`<button class="text-button" data-action="clear-history">${txt('清除本机记录','CLEAR LOCAL HISTORY')}</button>`:''}`,'history');}
function start(){audio.init();audio.effect('stage');$('overlay').hidden=true;modalType='';resultData=null;g.start();}
function stageBanner(stage){clearTimeout(bannerTimer);const el=$('stageBanner');el.innerHTML=`<small>${STAGES[stage].subtitle[L()]}</small><strong>${STAGES[stage].name[L()]}</strong>`;el.hidden=false;bannerTimer=setTimeout(()=>el.hidden=true,2300);}
g.on(e=>{
  if(e.type==='stage'){modalType='';$('overlay').hidden=true;stageBanner(e.stage);audio.effect('stage');notice(e.stage===2?txt('缄默之王正在苏醒','THE HOLLOW KING AWAKENS'):txt('守住誓约，穿越遗迹','HOLD YOUR OATH. CROSS THE RUINS.'),false,2500);updateUI();}
  if(e.type==='wave'){if(e.wave===1&&g.stage===0)notice(txt('点击挥剑 · 按住举盾 · 点击地面移动','TAP ATTACK · HOLD GUARD · TAP GROUND TO MOVE'),false,6500);else if(g.stage<2)notice(txt(`第 ${e.wave} 波敌人来袭`,`WAVE ${e.wave} APPROACHES`),false,1800);}
  if(e.type==='loot'){audio.effect('choose');renderLoot();}
  if(e.type==='pause')renderPause();
  if(e.type==='warning'&&e.kind==='quake'){audio.effect('warning');notice(txt('地面震击！离开红圈或闪避','GROUND QUAKE! LEAVE RED OR DODGE'),true,1700);}
  if(e.type==='perfect'){audio.effect('perfect');notice(txt('完美格挡！点击挥剑反击','PERFECT PARRY! TAP ATTACK TO RIPOSTE'),false,2000);}
  if(e.type==='summon')notice(txt('暗影援军来袭 · 用爆发清场','SHADOWS APPROACH · CLEAR THEM WITH BURST'),true,3000);
  if(e.type==='skill')audio.effect(e.skill);
  if(['swing','attack','hurt','slam','block','dodge'].includes(e.type))audio.effect(e.type);if(e.type==='controlMode')toast(e.auto?txt('自动攻击已开启，仍可手动防守和闪避','Auto attacks on. Guard and dodge remain manual.'):txt('已切换手动，点击挥剑发动攻击','Manual mode. Tap Attack to swing.'));if(e.type==='guardBreak')notice(txt('耐力耗尽，架势破碎！','STAMINA EMPTY — GUARD BROKEN'),true,1500);
  if(e.type==='home'){clearTimeout(bannerTimer);$('stageBanner').hidden=true;$('combatNotice').style.opacity=0;$('overlay').hidden=true;modalType='';updateUI();}
  if(e.type==='result'){resultData={won:e.won,stats:structuredClone(e.stats)};saved.runs=[resultData.stats,...(saved.runs||[])].slice(0,5);persist();audio.effect(e.won?'win':'lose');setTimeout(()=>{if(g.mode==='result')renderResult();},700);}
});
function openInfo(which){if(g.mode==='battle')g.pause();if(which==='howto')renderHowto();else if(which==='about')renderAbout();else renderHistory();}
$('language').onclick=()=>{lang=lang==='zh'?'en':'zh';saved.lang=lang;persist();setLanguage();};$('sound').onclick=()=>{audio.init();audio.setEnabled(!audio.enabled);saved.sound=audio.enabled;persist();updateSound();if(audio.enabled)audio.effect('choose');};$('start').onclick=start;$('pause').onclick=()=>g.pause();$('burst').onclick=()=>g.skill('burst');$('attack').onclick=()=>g.requestAttack();$('dodge').onclick=()=>g.skill('dodge');$('autoMode').onclick=()=>{g.setAuto(!g.hero.auto);updateUI();};$('howTo').onclick=()=>openInfo('howto');$('homeMark').onclick=()=>openInfo('about');$('recordsButton').onclick=()=>openInfo('history');
$('burstIcon').innerHTML=icon('burst');$('guardIcon').innerHTML=icon('shield');$('pause').innerHTML=icon('pause');
$('overlay').addEventListener('click',e=>{const button=e.target.closest('button');if(!button)return;if(button.dataset.item){audio.effect('choose');g.choose(button.dataset.item);return;}if(button.dataset.history!==undefined){const stats=saved.runs[Number(button.dataset.history)];resultData={won:stats.won,stats};renderDetails();return;}switch(button.dataset.action){case'resume':closeModal();break;case'restart':start();break;case'home':g.home();break;case'howto':renderHowto();break;case'close':closeModal();break;case'details':renderDetails();break;case'result':if(g.mode==='result')renderResult();else renderHistory();break;case'clear-history':saved.runs=[];persist();renderHistory();toast(txt('本机记录已清除','Local history cleared'));break;case'export':{const blob=new Blob([JSON.stringify(resultData.stats,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='rune-expedition-run.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast(txt('本局记录已保存','Run data saved'));break;}}});
const heldKeys=new Set();let guardPointer=null;
function keyboardMove(){g.setMoveInput((heldKeys.has('d')||heldKeys.has('arrowright')?1:0)-(heldKeys.has('a')||heldKeys.has('arrowleft')?1:0),(heldKeys.has('s')||heldKeys.has('arrowdown')?1:0)-(heldKeys.has('w')||heldKeys.has('arrowup')?1:0));}
const guardKeys=['q','k','2'];
$('guard').addEventListener('pointerdown',e=>{if(guardPointer!==null)return;e.preventDefault();audio.init();guardPointer=e.pointerId;$('guard').setPointerCapture(e.pointerId);g.setGuard(true);updateUI();});
function releaseGuard(e){if(e&&e.pointerId!==guardPointer)return;guardPointer=null;if(!guardKeys.some(k=>heldKeys.has(k)))g.setGuard(false);}
for(const event of ['pointerup','pointercancel','lostpointercapture'])$('guard').addEventListener(event,releaseGuard);
$('guard').addEventListener('contextmenu',e=>e.preventDefault());
$('scene').addEventListener('pointerdown',e=>{if(g.mode!=='battle')return;e.preventDefault();const p=art.screenToWorld(e.clientX,e.clientY);const target=g.enemies.filter(v=>!v.dying&&Math.abs(v.x-p.x)<v.radius+12&&p.y<v.y+15&&p.y>v.y-(v.kind==='boss'?180:90)).sort((a,b)=>b.y-a.y)[0];if(target)g.selectTarget(target.id);else g.moveTo(p.x,p.y);});
document.addEventListener('keydown',e=>{
 if(e.key==='Tab'&&!$('overlay').hidden){const buttons=[...$('overlayContent').querySelectorAll('button')];if(!buttons.length)return;const first=buttons[0],last=buttons.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}return;}
 if(e.key==='Escape'){e.preventDefault();if(g.mode==='battle')g.pause();else if(g.mode==='paused')closeModal();else if(['howto','about','history'].includes(modalType))closeModal();return;}
 if(g.mode!=='battle')return;const key=e.key.toLowerCase();if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright'].includes(key)){e.preventDefault();heldKeys.add(key);keyboardMove();return;}
 if(guardKeys.includes(key)){e.preventDefault();if(!e.repeat){heldKeys.add(key);g.setGuard(true);}return;}
 if(['j','1',' ','l','3','e','4','m'].includes(key)){e.preventDefault();if(e.repeat)return;if(['j','1'].includes(key))g.requestAttack();else if([' ','l','3'].includes(key))g.skill('dodge');else if(['e','4'].includes(key))g.skill('burst');else g.setAuto(!g.hero.auto);}
});
document.addEventListener('keyup',e=>{heldKeys.delete(e.key.toLowerCase());keyboardMove();if(guardKeys.includes(e.key.toLowerCase())&&guardPointer===null&&!guardKeys.some(k=>heldKeys.has(k)))g.setGuard(false);});
function clearInputs(){heldKeys.clear();guardPointer=null;g.resetInput();}
g.on(e=>{if(['pause','home','loot','result','stage'].includes(e.type))clearInputs();});
window.addEventListener('blur',()=>{clearInputs();if(g.mode==='battle')g.pause();});
document.addEventListener('visibilitychange',()=>{if(document.hidden){clearInputs();if(g.mode==='battle')g.pause();}});
function resize(){art.resize();fitArena();}window.addEventListener('resize',resize);new ResizeObserver(resize).observe($('game'));
let last=performance.now(),uiTimer=0;function frame(now){const dt=Math.min(.04,(now-last)/1000);last=now;g.update(dt);art.render(g);audio.tick(g.mode,g.stage);uiTimer+=dt;if(uiTimer>.06){updateUI();uiTimer=0;}requestAnimationFrame(frame);}setLanguage();requestAnimationFrame(frame);
