import {Expedition,ITEMS,STAGES} from './engine.js?v=2';
import {WorldArt,icon} from './art.js?v=2';
import {RuneAudio} from './audio.js?v=2';
const $=id=>document.getElementById(id);
const STORE='rune-expedition-v1';
function readStore(){try{return JSON.parse(localStorage.getItem(STORE)||'{}')||{};}catch{return {};}}
let saved=readStore(),lang=saved.lang==='en'?'en':'zh',modalType='',lastFocus=null,resultData=null,bannerTimer,noticeTimer,toastTimer;
const L=()=>lang==='zh'?0:1,txt=(zh,en)=>lang==='zh'?zh:en;
const g=new Expedition(),art=new WorldArt($('scene')),audio=new RuneAudio();audio.enabled=saved.sound!==false;
function persist(){try{localStorage.setItem(STORE,JSON.stringify(saved));}catch{}}
function seconds(t){return Math.floor(t/60).toString().padStart(2,'0')+':'+Math.floor(t%60).toString().padStart(2,'0');}
function itemName(id){return ITEMS[id].name[L()];}
function modal(html,type){lastFocus=document.activeElement;$('overlayContent').innerHTML=html;$('overlay').hidden=false;modalType=type;requestAnimationFrame(()=>{$('overlayContent').querySelector('button')?.focus({preventScroll:true});});}
function closeModal(){const old=modalType;modalType='';$('overlay').hidden=true;if(g.mode==='paused')g.resume();else if(g.mode==='loot')renderLoot();else if(g.mode==='result'&&old!=='result')renderResult();else if(lastFocus?.isConnected)lastFocus.focus({preventScroll:true});}
function toast(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2300);}
function notice(message,danger=false,duration=2800){$('combatNotice').textContent=message;$('combatNotice').classList.toggle('danger',danger);$('combatNotice').style.opacity=1;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('combatNotice').style.opacity=0,duration);}
function setLanguage(){
  document.documentElement.lang=lang==='zh'?'zh-CN':'en';$('language').textContent=lang==='zh'?'EN':'中';$('language').setAttribute('aria-label',txt('Switch to English','切换为中文'));
  $('gameTitle').innerHTML=txt('符文远征','RUNE<br>EXPEDITION');$('gameTitle').classList.toggle('english',lang==='en');document.querySelector('.english-title').textContent=txt('RUNE EXPEDITION','A DARK FANTASY ADVENTURE');
  $('homeEyebrow').textContent=txt('第一章 · 灰烬之门','CHAPTER I · THE ASHEN GATE');$('tagline').textContent=txt('碑文已碎，守门者仍在。\n带回那枚熄灭的符文。','The inscription is broken. The guardian remains.\nBring the forgotten rune back to life.');
  $('heroTag').textContent=txt('最后的守誓者','THE LAST OATHKEEPER');$('heroClass').textContent=txt('符文骑士','RUNE KNIGHT');$('startLabel').textContent=txt('踏入遗迹','ENTER THE RUINS');$('sessionNote').textContent=txt('自动战斗 · 装备构筑 · 约 3 分钟','AUTO COMBAT · BUILD YOUR GEAR · ~3 MIN');$('howTo').textContent=txt('远征指南','HOW TO PLAY');$('recordsButton').textContent=txt('远征记录','RUN HISTORY');
  $('burstLabel').textContent=txt('符文爆发','RUNE BURST');$('guardLabel').textContent=txt('誓约护盾','OATH SHIELD');$('burstHint').textContent=txt('全场伤害 · 8秒冷却','AREA DAMAGE · 8s');$('guardHint').textContent=txt('抵挡重击 · 11秒冷却','BLOCK DAMAGE · 11s');$('heroName').textContent=txt('守誓者','OATHKEEPER');$('bossName').textContent=txt('缄默之王','THE HOLLOW KING');
  $('pause').setAttribute('aria-label',txt('暂停游戏','Pause game'));$('scene').setAttribute('aria-label',txt('符文远征战场','Rune Expedition battlefield'));$('homeMark').setAttribute('aria-label',txt('作品说明','About this demo'));updateSound();updateUI();
  if(modalType==='loot')renderLoot();if(modalType==='pause')renderPause();if(modalType==='howto')renderHowto();if(modalType==='about')renderAbout();if(modalType==='history')renderHistory();if(modalType==='result')renderResult();if(modalType==='details')renderDetails();
  if(g.mode==='battle')notice(txt('自动攻击中 · 点击下方技能掌控战局','AUTO ATTACKING · TAP SKILLS TO TURN THE TIDE'),false,2200);
}
function updateSound(){$('sound').innerHTML=icon(audio.enabled?'sound':'mute');$('sound').setAttribute('aria-label',audio.enabled?txt('关闭声音','Mute sound'):txt('开启声音','Enable sound'));$('sound').setAttribute('aria-pressed',String(audio.enabled));}
function updateUI(){
  const h=g.hero,active=g.mode!=='home';$('home').hidden=active;$('hud').hidden=!active;$('controls').hidden=!active;$('pause').hidden=!['battle','paused'].includes(g.mode);
  if(!active)return;
  $('chapterLabel').textContent=`0${g.stage+1} / ${STAGES[g.stage].name[L()]}`;$('waveLabel').textContent=g.stage===2?txt('最终试炼','FINAL TRIAL'):txt(`第 ${Math.max(1,g.wave)} / 3 波`,`WAVE ${Math.max(1,g.wave)} / 3`);
  $('healthText').textContent=`${Math.ceil(h.hp)} / ${h.maxHp}`+(h.shield>0?` +${Math.ceil(h.shield)}`:'');$('healthFill').style.width=(h.hp/h.maxHp*100)+'%';$('shieldFill').style.width=Math.min(100,h.shield/h.maxHp*100)+'%';$('attackStat').textContent=txt('攻击 ','ATK ')+h.attack;$('critStat').textContent=txt('暴击 ','CRIT ')+Math.round(h.crit*100)+'%';$('goldStat').textContent=txt('灵魂碎片 ','SOULS ')+(g.stats?.coins||0);
  const boss=g.enemies.find(e=>e.kind==='boss'&&!e.dying);$('bossHud').hidden=!boss;if(boss){$('bossHealth').textContent=`${Math.ceil(boss.hp)} / ${boss.maxHp}`;$('bossFill').style.width=(boss.hp/boss.maxHp*100)+'%';}
  for(const [name,cd,total]of[['burst',h.burstCd,8],['guard',h.guardCd,11]]){const b=$(name);b.classList.toggle('on-cooldown',cd>.03);b.style.setProperty('--cd',Math.min(1,cd/total));$(name+'Cd').textContent=Math.ceil(cd)+'s';b.disabled=cd>0||g.mode!=='battle';}
  $('guard').classList.toggle('ready-pulse',!!boss?.telegraph&&h.guardCd<=0);$('burst').classList.toggle('ready-pulse',g.time<16&&h.burstCd===0&&g.enemies.length>0);
  const equipment=h.items.map(id=>`<span>${icon(ITEMS[id].icon)}${itemName(id)}</span>`).join('');if($('equipped').innerHTML!==equipment)$('equipped').innerHTML=equipment;
  document.querySelectorAll('.chapter-progress i').forEach((el,i)=>{el.className=i<g.stage?'done':i===g.stage?'current':'';});
  $('battleHint').textContent=txt('骑士自动追击 · 手动技能决定胜负','AUTO ATTACK · YOUR SKILLS MAKE THE DIFFERENCE');
}
function renderLoot(){const chapter=g.stage;modal(`<div class="eyebrow">${txt('遗迹馈赠','RELIC DISCOVERED')}</div><h2 id="overlayTitle">${txt('选择你的力量','CHOOSE YOUR POWER')}</h2><p class="subcopy">${txt('每次选择，都会改变接下来的战斗。','Every choice shapes the battles ahead.')}</p><div class="loot-list">${g.choices.map(id=>{const it=ITEMS[id];return `<button class="loot-card" data-item="${id}"><span class="item-art" style="color:${it.color}">${icon(it.icon)}</span><span><strong>${it.name[L()]}</strong><small>${it.desc[L()]}</small><span class="item-tag">${it.tag[L()]}</span></span><span class="select-arrow">›</span></button>`;}).join('')}</div><p class="recovery-note">${txt('选择后回复 38% 最大生命，并重置技能冷却。','Restore 38% of max HP and reset skill cooldowns.')}</p><p class="small-note">${txt('下一站：','NEXT: ')}${STAGES[chapter+1].name[L()]}</p>`,'loot');}
function renderPause(){modal(`<div class="eyebrow">${txt('暂歇于遗迹之间','A MOMENT BETWEEN BATTLES')}</div><h2 id="overlayTitle">${txt('远征已暂停','EXPEDITION PAUSED')}</h2><p class="subcopy">${txt('深呼吸。下一次挥剑，为你而起。','Take a breath. The next strike is yours.')}</p><button class="primary-button" data-action="resume">${txt('继续远征','RESUME')}</button><button class="secondary-button" data-action="howto">${txt('查看远征指南','HOW TO PLAY')}</button><button class="text-button" data-action="home">${txt('结束本局，返回入口','END RUN & RETURN')}</button>`,'pause');}
function renderHowto(){modal(`<div class="eyebrow">FIELD GUIDE</div><h2 id="overlayTitle">${txt('远征指南','YOUR FIELD GUIDE')}</h2><div class="howto-row"><span>01</span><div><strong>${txt('你来决策，骑士来战斗','The knight fights. You decide.')}</strong><p>${txt('骑士会自动接近并攻击敌人，无需移动。点击「符文爆发」对场上敌人造成伤害。','Your knight moves and attacks automatically. Tap Rune Burst to damage every enemy on the field.')}</p></div></div><div class="howto-row"><span>02</span><div><strong>${txt('在重击落下前，举起护盾','Raise your shield before impact.')}</strong><p>${txt('Boss脚下出现红色预警时，点击「誓约护盾」。护盾持续约4秒，能够抵挡蓄力重击。','When the boss marks a red warning circle, tap Oath Shield. Its four-second protection can absorb the heavy strike.')}</p></div></div><div class="howto-row"><span>03</span><div><strong>${txt('两次选择，构筑你的流派','Two choices. Your own build.')}</strong><p>${txt('前两场战斗后，各选择一件装备。灼烧、暴击或守护，尝试不同组合，再挑战缄默之王。','Choose a relic after each of the first two battles. Combine burn, critical hits, or protection to face the Hollow King.')}</p></div></div><p class="small-note">${txt('电脑快捷键：1 / 空格释放爆发，2 / Q开启护盾，Esc暂停。','KEYBOARD: 1 / Space for Burst, 2 / Q for Shield, Esc to pause.')}</p><button class="secondary-button" data-action="close">${txt('明白了','GOT IT')}</button>`,'howto');}
function renderAbout(){modal(`<div class="eyebrow">AN ORIGINAL DEMO BY CASSIE</div><h2 id="overlayTitle">${txt('符文远征','RUNE EXPEDITION')}</h2><p class="subcopy">${txt('一段关于抉择、成长与最后一击的暗黑奇幻远征。','A dark-fantasy expedition about choices, growth, and the final strike.')}</p><div class="howto-row"><span>ᛟ</span><div><strong>${txt('小小旅程，完整冒险','A small journey. A complete adventure.')}</strong><p>${txt('三场战斗、六件可选装备、一个最终Boss。支持中英文切换，手机与电脑均可试玩。','Three battles, six selectable relics, and one final boss. Play in Chinese or English, on mobile or desktop.')}</p></div></div><p class="small-note">${txt('这是借助 AI 编程工具制作的个人原创试玩作品。美术由程序绘制，音乐与音效实时合成。战斗记录仅保存在当前浏览器，可在远征记录中清除。','An original personal demo built with AI coding assistance. Artwork is drawn procedurally; music and sound are synthesized in real time. Run history stays in this browser and can be cleared.')}</p><button class="secondary-button" data-action="close">${txt('返回','BACK')}</button>`,'about');}
function renderResult(){if(!resultData)return;const {won,stats}=resultData;modal(`<div class="result-seal ${won?'':'defeat'}">${won?'ᛟ':'ᚾ'}</div><div class="eyebrow">${won?'EXPEDITION COMPLETE':'THE OATH REMAINS'}</div><h2 id="overlayTitle">${won?txt('符文重燃','THE RUNE AWAKENS'):txt('誓约未尽','RISE AGAIN')}</h2><p class="subcopy">${won?txt('长夜退去。你带回了遗迹最后的光。','The long night recedes. You return with its final light.'):txt('这次远征暂告结束。换一种选择，再次出发。','This expedition ends here. A new choice may change your fate.')}</p><div class="result-stats"><div><strong>${seconds(stats.time)}</strong><span>${txt('战斗用时','BATTLE TIME')}</span></div><div><strong>${stats.kills}</strong><span>${txt('击败敌人','ENEMIES SLAIN')}</span></div><div><strong>${stats.damage.toLocaleString()}</strong><span>${txt('累计伤害','TOTAL DAMAGE')}</span></div></div><div class="result-build">${stats.items.map(id=>`<span>${itemName(id)}</span>`).join('')}</div><p class="result-tip">${won?txt('下一次，试试不同的装备组合。','Try a different relic combination on your next run.'):txt('在红色预警出现时开启护盾，可以抵挡Boss重击。','Activate your shield during the red warning to block the boss’s heavy strike.')}</p><button class="primary-button" data-action="restart">${txt('再次远征','ANOTHER EXPEDITION')}</button><button class="secondary-button" data-action="details">${txt('查看战斗回顾','VIEW BATTLE RECAP')}</button><button class="text-button" data-action="home">${txt('返回入口','RETURN TO THE GATE')}</button>`,'result');}
function renderDetails(){const s=resultData?.stats;if(!s)return;const rows=[[txt('战斗用时','Battle time'),seconds(s.time)],[txt('完成关卡','Stages cleared'),`${s.stages.length} / 3`],[txt('累计伤害','Damage dealt'),s.damage],[txt('承受伤害','Damage received'),s.received],[txt('护盾抵挡','Damage blocked'),s.blocked],[txt('暴击次数','Critical hits'),s.crits],[txt('爆发使用','Rune Bursts'),s.burst],[txt('护盾使用','Shields used'),s.guard],[txt('成功抵挡重击','Heavy strikes blocked'),s.perfectGuards],[txt('灵魂碎片','Soul shards'),s.coins]];modal(`<div class="eyebrow">BATTLE RECAP</div><h2 id="overlayTitle">${txt('每次选择都有回响','EVERY CHOICE ECHOES')}</h2><table class="data-table">${rows.map(([k,v])=>`<tr><td>${k}</td><td>${v}</td></tr>`).join('')}</table><p class="small-note">${txt('以上为本局实际记录。仅保存在当前浏览器，不上传个人信息。','Actual results from this run. Stored in this browser only.')}</p><button class="secondary-button" data-action="export">${txt('保存本局记录','SAVE RUN DATA')}</button><button class="text-button" data-action="result">${txt('返回结算','BACK TO RESULTS')}</button>`,'details');}
function renderHistory(){const runs=saved.runs||[];modal(`<div class="eyebrow">YOUR EXPEDITIONS</div><h2 id="overlayTitle">${txt('远征记录','RUN HISTORY')}</h2><p class="subcopy">${runs.length?txt('保存在此浏览器的最近 5 次远征。','Your last five expeditions on this browser.'):txt('遗迹正等待你的第一步。','The ruins await your first step.')}</p>${runs.map((r,i)=>`<button class="loot-card" data-history="${i}"><span class="item-art">${r.won?'ᛟ':'ᚾ'}</span><span><strong>${r.won?txt('符文重燃','RUNE AWAKENED'):txt('誓约未尽','OATH UNFINISHED')}</strong><small>${seconds(r.time)} · ${r.kills} ${txt('击败','slain')} · ${r.items.map(itemName).join(' / ')||txt('初始装备','Starting gear')}</small></span><span class="select-arrow">›</span></button>`).join('')}<button class="secondary-button" data-action="close">${txt('返回','BACK')}</button>${runs.length?`<button class="text-button" data-action="clear-history">${txt('清除本机记录','CLEAR LOCAL HISTORY')}</button>`:''}`,'history');}
function start(){audio.init();audio.effect('stage');$('overlay').hidden=true;modalType='';resultData=null;g.start();}
function stageBanner(stage){clearTimeout(bannerTimer);const el=$('stageBanner');el.innerHTML=`<small>${STAGES[stage].subtitle[L()]}</small><strong>${STAGES[stage].name[L()]}</strong>`;el.hidden=false;bannerTimer=setTimeout(()=>el.hidden=true,2300);}
g.on(e=>{
  if(e.type==='stage'){modalType='';$('overlay').hidden=true;stageBanner(e.stage);audio.effect('stage');notice(e.stage===2?txt('缄默之王正在苏醒','THE HOLLOW KING AWAKENS'):txt('守住誓约，穿越遗迹','HOLD YOUR OATH. CROSS THE RUINS.'),false,2500);updateUI();}
  if(e.type==='wave'){if(e.wave===1&&g.stage===0)notice(txt('自动攻击中 · 点击「符文爆发」清理敌人','AUTO ATTACKING · TAP RUNE BURST TO STRIKE'),false,6500);else if(g.stage<2)notice(txt(`第 ${e.wave} 波敌人来袭`,`WAVE ${e.wave} APPROACHES`),false,1800);}
  if(e.type==='loot'){audio.effect('choose');renderLoot();}
  if(e.type==='pause')renderPause();
  if(e.type==='warning'){audio.effect('warning');notice(txt('重击蓄力！现在开启护盾','HEAVY STRIKE! RAISE YOUR SHIELD'),true,2300);}
  if(e.type==='perfect'){audio.effect('perfect');notice(txt('重击已抵挡 · 誓约不破','HEAVY STRIKE BLOCKED · OATH UNBROKEN'),false,2000);}
  if(e.type==='summon')notice(txt('暗影援军来袭 · 用爆发清场','SHADOWS APPROACH · CLEAR THEM WITH BURST'),true,3000);
  if(e.type==='skill')audio.effect(e.skill);
  if(['attack','hurt','slam'].includes(e.type))audio.effect(e.type);
  if(e.type==='home'){clearTimeout(bannerTimer);$('stageBanner').hidden=true;$('combatNotice').style.opacity=0;$('overlay').hidden=true;modalType='';updateUI();}
  if(e.type==='result'){resultData={won:e.won,stats:structuredClone(e.stats)};saved.runs=[resultData.stats,...(saved.runs||[])].slice(0,5);persist();audio.effect(e.won?'win':'lose');setTimeout(()=>{if(g.mode==='result')renderResult();},700);}
});
function openInfo(which){if(g.mode==='battle')g.pause();if(which==='howto')renderHowto();else if(which==='about')renderAbout();else renderHistory();}
$('language').onclick=()=>{lang=lang==='zh'?'en':'zh';saved.lang=lang;persist();setLanguage();};$('sound').onclick=()=>{audio.init();audio.setEnabled(!audio.enabled);saved.sound=audio.enabled;persist();updateSound();if(audio.enabled)audio.effect('choose');};$('start').onclick=start;$('pause').onclick=()=>g.pause();$('burst').onclick=()=>g.skill('burst');$('guard').onclick=()=>g.skill('guard');$('howTo').onclick=()=>openInfo('howto');$('homeMark').onclick=()=>openInfo('about');$('recordsButton').onclick=()=>openInfo('history');
$('burstIcon').innerHTML=icon('burst');$('guardIcon').innerHTML=icon('shield');$('pause').innerHTML=icon('pause');
$('overlay').addEventListener('click',e=>{const button=e.target.closest('button');if(!button)return;if(button.dataset.item){audio.effect('choose');g.choose(button.dataset.item);return;}if(button.dataset.history!==undefined){const stats=saved.runs[Number(button.dataset.history)];resultData={won:stats.won,stats};renderDetails();return;}switch(button.dataset.action){case'resume':closeModal();break;case'restart':start();break;case'home':g.home();break;case'howto':renderHowto();break;case'close':closeModal();break;case'details':renderDetails();break;case'result':if(g.mode==='result')renderResult();else renderHistory();break;case'clear-history':saved.runs=[];persist();renderHistory();toast(txt('本机记录已清除','Local history cleared'));break;case'export':{const blob=new Blob([JSON.stringify(resultData.stats,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='rune-expedition-run.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast(txt('本局记录已保存','Run data saved'));break;}}});
document.addEventListener('keydown',e=>{
  if(e.key==='Tab'&&!$('overlay').hidden){const buttons=[...$('overlayContent').querySelectorAll('button')];if(!buttons.length)return;const first=buttons[0],last=buttons.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}return;}
  if(e.key==='Escape'){e.preventDefault();if(g.mode==='battle')g.pause();else if(g.mode==='paused')closeModal();else if(['howto','about','history'].includes(modalType))closeModal();return;}
  if(g.mode==='battle'&&!e.repeat){if(['1',' '].includes(e.key)){e.preventDefault();g.skill('burst');}if(['2','q','Q'].includes(e.key)){e.preventDefault();g.skill('guard');}}
});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&g.mode==='battle')g.pause();});
window.addEventListener('resize',()=>art.resize());new ResizeObserver(()=>art.resize()).observe($('game'));
let last=performance.now(),uiTimer=0;function frame(now){const dt=Math.min(.04,(now-last)/1000);last=now;g.update(dt);art.render(g);audio.tick(g.mode,g.stage);uiTimer+=dt;if(uiTimer>.08){updateUI();uiTimer=0;}requestAnimationFrame(frame);}setLanguage();requestAnimationFrame(frame);
